package com.eventura.entities;
// Generated Jun 12, 2025, 2:02:47 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * ActivityLog generated by hbm2java
 */
@Entity
@Table(name = "activity_log")
public class ActivityLog implements java.io.Serializable {

	private int id;
	private Users users;
	private String deviceLog;
	private String ipLog;
	private Date createdAt;
	private Date updatedAt;

	public ActivityLog() {
	}

	public ActivityLog(int id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ActivityLog(int id, Users users, String deviceLog, String ipLog, Date createdAt, Date updatedAt) {
		this.id = id;
		this.users = users;
		this.deviceLog = deviceLog;
		this.ipLog = ipLog;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "device_log")
	public String getDeviceLog() {
		return this.deviceLog;
	}

	public void setDeviceLog(String deviceLog) {
		this.deviceLog = deviceLog;
	}

	@Column(name = "ip_log")
	public String getIpLog() {
		return this.ipLog;
	}

	public void setIpLog(String ipLog) {
		this.ipLog = ipLog;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
