package com.eventura.entities;
// Generated Jun 19, 2025, 10:38:50 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * AdministrativeUnits generated by hbm2java
 */
@Entity
@Table(name = "administrative_units")
public class AdministrativeUnits implements java.io.Serializable {

	private int id;
	private String fullName;
	private String fullNameEn;
	private String shortName;
	private String shortNameEn;
	private String codeName;
	private String codeNameEn;
	private Set<Provinces> provinceses = new HashSet<Provinces>(0);
	private Set<Districts> districtses = new HashSet<Districts>(0);
	private Set<Wards> wardses = new HashSet<Wards>(0);

	public AdministrativeUnits() {
	}

	public AdministrativeUnits(int id) {
		this.id = id;
	}

	public AdministrativeUnits(int id, String fullName, String fullNameEn, String shortName, String shortNameEn,
			String codeName, String codeNameEn, Set<Provinces> provinceses, Set<Districts> districtses,
			Set<Wards> wardses) {
		this.id = id;
		this.fullName = fullName;
		this.fullNameEn = fullNameEn;
		this.shortName = shortName;
		this.shortNameEn = shortNameEn;
		this.codeName = codeName;
		this.codeNameEn = codeNameEn;
		this.provinceses = provinceses;
		this.districtses = districtses;
		this.wardses = wardses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "full_name")
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "full_name_en")
	public String getFullNameEn() {
		return this.fullNameEn;
	}

	public void setFullNameEn(String fullNameEn) {
		this.fullNameEn = fullNameEn;
	}

	@Column(name = "short_name")
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "short_name_en")
	public String getShortNameEn() {
		return this.shortNameEn;
	}

	public void setShortNameEn(String shortNameEn) {
		this.shortNameEn = shortNameEn;
	}

	@Column(name = "code_name")
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	@Column(name = "code_name_en")
	public String getCodeNameEn() {
		return this.codeNameEn;
	}

	public void setCodeNameEn(String codeNameEn) {
		this.codeNameEn = codeNameEn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrativeUnits")
	public Set<Provinces> getProvinceses() {
		return this.provinceses;
	}

	public void setProvinceses(Set<Provinces> provinceses) {
		this.provinceses = provinceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrativeUnits")
	public Set<Districts> getDistrictses() {
		return this.districtses;
	}

	public void setDistrictses(Set<Districts> districtses) {
		this.districtses = districtses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrativeUnits")
	public Set<Wards> getWardses() {
		return this.wardses;
	}

	public void setWardses(Set<Wards> wardses) {
		this.wardses = wardses;
	}

}
