package com.eventura.entities;
// Generated Jun 23, 2025, 6:51:08 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * CampaignRedemptions generated by hbm2java
 */
@Entity
@Table(name = "campaign_redemptions")
public class CampaignRedemptions implements java.io.Serializable {

	private Integer id;
	private String campaignName;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set<OrdersCampaigns> ordersCampaignses = new HashSet<OrdersCampaigns>(0);
	private Set<CouponsCampaigns> couponsCampaignses = new HashSet<CouponsCampaigns>(0);
	private Set<VouchersCampaigns> vouchersCampaignses = new HashSet<VouchersCampaigns>(0);

	public CampaignRedemptions() {
	}

	public CampaignRedemptions(String campaignName, Date createdAt, Date updatedAt) {
		this.campaignName = campaignName;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public CampaignRedemptions(String campaignName, Date createdAt, Date updatedAt, Date deletedAt,
			Set<OrdersCampaigns> ordersCampaignses, Set<CouponsCampaigns> couponsCampaignses,
			Set<VouchersCampaigns> vouchersCampaignses) {
		this.campaignName = campaignName;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.ordersCampaignses = ordersCampaignses;
		this.couponsCampaignses = couponsCampaignses;
		this.vouchersCampaignses = vouchersCampaignses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "campaign_name", nullable = false)
	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 19)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "campaignRedemptions")
	public Set<OrdersCampaigns> getOrdersCampaignses() {
		return this.ordersCampaignses;
	}

	public void setOrdersCampaignses(Set<OrdersCampaigns> ordersCampaignses) {
		this.ordersCampaignses = ordersCampaignses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "campaignRedemptions")
	public Set<CouponsCampaigns> getCouponsCampaignses() {
		return this.couponsCampaignses;
	}

	public void setCouponsCampaignses(Set<CouponsCampaigns> couponsCampaignses) {
		this.couponsCampaignses = couponsCampaignses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "campaignRedemptions")
	public Set<VouchersCampaigns> getVouchersCampaignses() {
		return this.vouchersCampaignses;
	}

	public void setVouchersCampaignses(Set<VouchersCampaigns> vouchersCampaignses) {
		this.vouchersCampaignses = vouchersCampaignses;
	}

}
