package com.eventura.entities;
// Generated Jun 19, 2025, 12:03:09 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * CampaignRedemptions generated by hbm2java
 */
@Entity
@Table(name = "campaign_redemptions", uniqueConstraints = @UniqueConstraint(columnNames = { "coupon_code",
		"voucher_code" }))
public class CampaignRedemptions implements java.io.Serializable {

	private Integer id;
	private String campaignName;
	private String couponCode;
	private String voucherCode;
	private Date redemptionDate;
	private int userId;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set<Coupons> couponses = new HashSet<Coupons>(0);
	private Set<Vouchers> voucherses = new HashSet<Vouchers>(0);

	public CampaignRedemptions() {
	}

	public CampaignRedemptions(String campaignName, String couponCode, String voucherCode, Date redemptionDate,
			int userId, Date createdAt, Date updatedAt) {
		this.campaignName = campaignName;
		this.couponCode = couponCode;
		this.voucherCode = voucherCode;
		this.redemptionDate = redemptionDate;
		this.userId = userId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public CampaignRedemptions(String campaignName, String couponCode, String voucherCode, Date redemptionDate,
			int userId, Date createdAt, Date updatedAt, Date deletedAt, Set<Coupons> couponses,
			Set<Vouchers> voucherses) {
		this.campaignName = campaignName;
		this.couponCode = couponCode;
		this.voucherCode = voucherCode;
		this.redemptionDate = redemptionDate;
		this.userId = userId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.couponses = couponses;
		this.voucherses = voucherses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "campaign_name", nullable = false)
	public String getCampaignName() {
		return this.campaignName;
	}

	public void setCampaignName(String campaignName) {
		this.campaignName = campaignName;
	}

	@Column(name = "coupon_code", nullable = false)
	public String getCouponCode() {
		return this.couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	@Column(name = "voucher_code", nullable = false)
	public String getVoucherCode() {
		return this.voucherCode;
	}

	public void setVoucherCode(String voucherCode) {
		this.voucherCode = voucherCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "redemption_date", nullable = false, length = 19)
	public Date getRedemptionDate() {
		return this.redemptionDate;
	}

	public void setRedemptionDate(Date redemptionDate) {
		this.redemptionDate = redemptionDate;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 19)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "campaignRedemptionses")
	public Set<Coupons> getCouponses() {
		return this.couponses;
	}

	public void setCouponses(Set<Coupons> couponses) {
		this.couponses = couponses;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "campaignRedemptionses")
	public Set<Vouchers> getVoucherses() {
		return this.voucherses;
	}

	public void setVoucherses(Set<Vouchers> voucherses) {
		this.voucherses = voucherses;
	}

}
