package com.eventura.entities;
// Generated Jul 2, 2025, 11:54:26 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Carts generated by hbm2java
 */
@Entity
@Table(name = "carts")
public class Carts implements java.io.Serializable {

	private Integer id;
	private Users users;
	private Date createdAt;
	private Date updatedAt;
	private Set<CartItems> cartItemses = new HashSet<CartItems>(0);

	public Carts() {
	}

	public Carts(Users users, Date createdAt, Date updatedAt) {
		this.users = users;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Carts(Users users, Date createdAt, Date updatedAt, Set<CartItems> cartItemses) {
		this.users = users;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.cartItemses = cartItemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "carts")
	public Set<CartItems> getCartItemses() {
		return this.cartItemses;
	}

	public void setCartItemses(Set<CartItems> cartItemses) {
		this.cartItemses = cartItemses;
	}

}
