package com.eventura.entities;
// Generated Jul 2, 2025, 11:54:26 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * CouponsCampaigns generated by hbm2java
 */
@Entity
@Table(name = "coupons_campaigns")
public class CouponsCampaigns implements java.io.Serializable {

	private String couponCode;
	private CampaignRedemptions campaignRedemptions;
	private Coupons coupons;
	private int redeemAllowedQty;
	private int redeemUsedQty;

	public CouponsCampaigns() {
	}

	public CouponsCampaigns(String couponCode, CampaignRedemptions campaignRedemptions, Coupons coupons,
			int redeemAllowedQty, int redeemUsedQty) {
		this.couponCode = couponCode;
		this.campaignRedemptions = campaignRedemptions;
		this.coupons = coupons;
		this.redeemAllowedQty = redeemAllowedQty;
		this.redeemUsedQty = redeemUsedQty;
	}

	@Id

	@Column(name = "coupon_code", unique = true, nullable = false)
	public String getCouponCode() {
		return this.couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "campaign_id", nullable = false)
	public CampaignRedemptions getCampaignRedemptions() {
		return this.campaignRedemptions;
	}

	public void setCampaignRedemptions(CampaignRedemptions campaignRedemptions) {
		this.campaignRedemptions = campaignRedemptions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id", nullable = false)
	public Coupons getCoupons() {
		return this.coupons;
	}

	public void setCoupons(Coupons coupons) {
		this.coupons = coupons;
	}

	@Column(name = "redeem_allowed_qty", nullable = false)
	public int getRedeemAllowedQty() {
		return this.redeemAllowedQty;
	}

	public void setRedeemAllowedQty(int redeemAllowedQty) {
		this.redeemAllowedQty = redeemAllowedQty;
	}

	@Column(name = "redeem_used_qty", nullable = false)
	public int getRedeemUsedQty() {
		return this.redeemUsedQty;
	}

	public void setRedeemUsedQty(int redeemUsedQty) {
		this.redeemUsedQty = redeemUsedQty;
	}

}
