package com.eventura.entities;
// Generated Jun 30, 2025, 6:31:20 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * CouponsCampaignsId generated by hbm2java
 */
@Embeddable
public class CouponsCampaignsId implements java.io.Serializable {

	private int couponId;
	private int campaignId;

	public CouponsCampaignsId() {
	}

	public CouponsCampaignsId(int couponId, int campaignId) {
		this.couponId = couponId;
		this.campaignId = campaignId;
	}

	@Column(name = "coupon_id", nullable = false)
	public int getCouponId() {
		return this.couponId;
	}

	public void setCouponId(int couponId) {
		this.couponId = couponId;
	}

	@Column(name = "campaign_id", nullable = false)
	public int getCampaignId() {
		return this.campaignId;
	}

	public void setCampaignId(int campaignId) {
		this.campaignId = campaignId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CouponsCampaignsId))
			return false;
		CouponsCampaignsId castOther = (CouponsCampaignsId) other;

		return (this.getCouponId() == castOther.getCouponId()) && (this.getCampaignId() == castOther.getCampaignId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCouponId();
		result = 37 * result + this.getCampaignId();
		return result;
	}

}
