package com.eventura.entities;
// Generated Jun 17, 2025, 7:55:23 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * CouponTypes generated by hbm2java
 */
@Entity
@Table(name = "coupon_types")
public class CouponTypes implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date createdAt;
	private Date upadetedAt;
	private Date deletedAt;
	private Set<Coupons> couponses = new HashSet<Coupons>(0);

	public CouponTypes() {
	}

	public CouponTypes(String name, Date createdAt, Date upadetedAt) {
		this.name = name;
		this.createdAt = createdAt;
		this.upadetedAt = upadetedAt;
	}

	public CouponTypes(String name, Date createdAt, Date upadetedAt, Date deletedAt, Set<Coupons> couponses) {
		this.name = name;
		this.createdAt = createdAt;
		this.upadetedAt = upadetedAt;
		this.deletedAt = deletedAt;
		this.couponses = couponses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "upadeted_at", nullable = false, length = 19)
	public Date getUpadetedAt() {
		return this.upadetedAt;
	}

	public void setUpadetedAt(Date upadetedAt) {
		this.upadetedAt = upadetedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 19)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "couponTypes")
	public Set<Coupons> getCouponses() {
		return this.couponses;
	}

	public void setCouponses(Set<Coupons> couponses) {
		this.couponses = couponses;
	}

}
