package com.eventura.entities;
// Generated Jun 24, 2025, 5:03:57 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * CouponsCampaigns generated by hbm2java
 */
@Entity
@Table(name = "coupons_campaigns")
public class CouponsCampaigns implements java.io.Serializable {

	private CouponsCampaignsId id;
	private CampaignRedemptions campaignRedemptions;
	private Coupons coupons;
	private String couponCode;
	private int redeemAllowedQty;
	private int redeemUsedQty;

	public CouponsCampaigns() {
	}

	public CouponsCampaigns(CouponsCampaignsId id, CampaignRedemptions campaignRedemptions, Coupons coupons,
			String couponCode, int redeemAllowedQty, int redeemUsedQty) {
		this.id = id;
		this.campaignRedemptions = campaignRedemptions;
		this.coupons = coupons;
		this.couponCode = couponCode;
		this.redeemAllowedQty = redeemAllowedQty;
		this.redeemUsedQty = redeemUsedQty;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "couponId", column = @Column(name = "coupon_id", nullable = false)),
			@AttributeOverride(name = "campaignId", column = @Column(name = "campaign_id", nullable = false)) })
	public CouponsCampaignsId getId() {
		return this.id;
	}

	public void setId(CouponsCampaignsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "campaign_id", nullable = false, insertable = false, updatable = false)
	public CampaignRedemptions getCampaignRedemptions() {
		return this.campaignRedemptions;
	}

	public void setCampaignRedemptions(CampaignRedemptions campaignRedemptions) {
		this.campaignRedemptions = campaignRedemptions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id", nullable = false, insertable = false, updatable = false)
	public Coupons getCoupons() {
		return this.coupons;
	}

	public void setCoupons(Coupons coupons) {
		this.coupons = coupons;
	}

	@Column(name = "coupon_code", nullable = false)
	public String getCouponCode() {
		return this.couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	@Column(name = "redeem_allowed_qty", nullable = false)
	public int getRedeemAllowedQty() {
		return this.redeemAllowedQty;
	}

	public void setRedeemAllowedQty(int redeemAllowedQty) {
		this.redeemAllowedQty = redeemAllowedQty;
	}

	@Column(name = "redeem_used_qty", nullable = false)
	public int getRedeemUsedQty() {
		return this.redeemUsedQty;
	}

	public void setRedeemUsedQty(int redeemUsedQty) {
		this.redeemUsedQty = redeemUsedQty;
	}

}
