package com.eventura.entities;
// Generated Jun 17, 2025, 7:55:23 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Coupons generated by hbm2java
 */
@Entity
@Table(name = "coupons")
public class Coupons implements java.io.Serializable {

	private Integer id;
	private CouponTypes couponTypes;
	private Vendors vendors;
	private int quantity;
	private Date exp;
	private Date startDate;
	private String couponCode;
	private String couponName;
	private double discountValue;
	private double minTotalOrder;
	private double maxDiscountValue;
	private boolean couponStatus;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set<OrdersCoupons> ordersCouponses = new HashSet<OrdersCoupons>(0);

	public Coupons() {
	}

	public Coupons(CouponTypes couponTypes, int quantity, Date exp, Date startDate, String couponCode,
			String couponName, double discountValue, double minTotalOrder, double maxDiscountValue,
			boolean couponStatus, Date createdAt, Date updatedAt) {
		this.couponTypes = couponTypes;
		this.quantity = quantity;
		this.exp = exp;
		this.startDate = startDate;
		this.couponCode = couponCode;
		this.couponName = couponName;
		this.discountValue = discountValue;
		this.minTotalOrder = minTotalOrder;
		this.maxDiscountValue = maxDiscountValue;
		this.couponStatus = couponStatus;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Coupons(CouponTypes couponTypes, Vendors vendors, int quantity, Date exp, Date startDate, String couponCode,
			String couponName, double discountValue, double minTotalOrder, double maxDiscountValue,
			boolean couponStatus, Date createdAt, Date updatedAt, Date deletedAt, Set<OrdersCoupons> ordersCouponses) {
		this.couponTypes = couponTypes;
		this.vendors = vendors;
		this.quantity = quantity;
		this.exp = exp;
		this.startDate = startDate;
		this.couponCode = couponCode;
		this.couponName = couponName;
		this.discountValue = discountValue;
		this.minTotalOrder = minTotalOrder;
		this.maxDiscountValue = maxDiscountValue;
		this.couponStatus = couponStatus;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.ordersCouponses = ordersCouponses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_type_id", nullable = false)
	public CouponTypes getCouponTypes() {
		return this.couponTypes;
	}

	public void setCouponTypes(CouponTypes couponTypes) {
		this.couponTypes = couponTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor_id")
	public Vendors getVendors() {
		return this.vendors;
	}

	public void setVendors(Vendors vendors) {
		this.vendors = vendors;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "exp", nullable = false, length = 19)
	public Date getExp() {
		return this.exp;
	}

	public void setExp(Date exp) {
		this.exp = exp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "coupon_code", nullable = false)
	public String getCouponCode() {
		return this.couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	@Column(name = "coupon_name", nullable = false)
	public String getCouponName() {
		return this.couponName;
	}

	public void setCouponName(String couponName) {
		this.couponName = couponName;
	}

	@Column(name = "discount_value", nullable = false, precision = 22, scale = 0)
	public double getDiscountValue() {
		return this.discountValue;
	}

	public void setDiscountValue(double discountValue) {
		this.discountValue = discountValue;
	}

	@Column(name = "min_total_order", nullable = false, precision = 22, scale = 0)
	public double getMinTotalOrder() {
		return this.minTotalOrder;
	}

	public void setMinTotalOrder(double minTotalOrder) {
		this.minTotalOrder = minTotalOrder;
	}

	@Column(name = "max_discount_value", nullable = false, precision = 22, scale = 0)
	public double getMaxDiscountValue() {
		return this.maxDiscountValue;
	}

	public void setMaxDiscountValue(double maxDiscountValue) {
		this.maxDiscountValue = maxDiscountValue;
	}

	@Column(name = "coupon_status", nullable = false)
	public boolean isCouponStatus() {
		return this.couponStatus;
	}

	public void setCouponStatus(boolean couponStatus) {
		this.couponStatus = couponStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 19)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupons")
	public Set<OrdersCoupons> getOrdersCouponses() {
		return this.ordersCouponses;
	}

	public void setOrdersCouponses(Set<OrdersCoupons> ordersCouponses) {
		this.ordersCouponses = ordersCouponses;
	}

}
