package com.eventura.entities;
// Generated Jun 19, 2025, 1:15:05 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * OrdersCoupons generated by hbm2java
 */
@Entity
@Table(name = "orders_coupons")
public class OrdersCoupons implements java.io.Serializable {

	private OrdersCouponsId id;
	private Coupons coupons;
	private Orders orders;
	private Date createdAt;

	public OrdersCoupons() {
	}

	public OrdersCoupons(OrdersCouponsId id, Coupons coupons, Orders orders, Date createdAt) {
		this.id = id;
		this.coupons = coupons;
		this.orders = orders;
		this.createdAt = createdAt;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false)),
			@AttributeOverride(name = "couponId", column = @Column(name = "coupon_id", nullable = false)) })
	public OrdersCouponsId getId() {
		return this.id;
	}

	public void setId(OrdersCouponsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id", nullable = false, insertable = false, updatable = false)
	public Coupons getCoupons() {
		return this.coupons;
	}

	public void setCoupons(Coupons coupons) {
		this.coupons = coupons;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
