package com.eventura.entities;
// Generated Jun 19, 2025, 1:15:05 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * OrderRefunds generated by hbm2java
 */
@Entity
@Table(name = "order_refunds")
public class OrderRefunds implements java.io.Serializable {

	private Integer id;
	private OrderReturns orderReturns;
	private Long amount;
	private String orderRefundsStatus;
	private Date createdAt;
	private Date updatedAt;
	private Date processedAt;

	public OrderRefunds() {
	}

	public OrderRefunds(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public OrderRefunds(OrderReturns orderReturns, Long amount, String orderRefundsStatus, Date createdAt,
			Date updatedAt, Date processedAt) {
		this.orderReturns = orderReturns;
		this.amount = amount;
		this.orderRefundsStatus = orderRefundsStatus;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.processedAt = processedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_returns_id")
	public OrderReturns getOrderReturns() {
		return this.orderReturns;
	}

	public void setOrderReturns(OrderReturns orderReturns) {
		this.orderReturns = orderReturns;
	}

	@Column(name = "amount", precision = 10, scale = 0)
	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	@Column(name = "order_refunds_status")
	public String getOrderRefundsStatus() {
		return this.orderRefundsStatus;
	}

	public void setOrderRefundsStatus(String orderRefundsStatus) {
		this.orderRefundsStatus = orderRefundsStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "processed_at", length = 19)
	public Date getProcessedAt() {
		return this.processedAt;
	}

	public void setProcessedAt(Date processedAt) {
		this.processedAt = processedAt;
	}

}
