package com.eventura.entities;
// Generated Jun 19, 2025, 10:47:09 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * OrdersCampaigns generated by hbm2java
 */
@Entity
@Table(name = "orders_campaigns")
public class OrdersCampaigns implements java.io.Serializable {

	private OrdersCampaignsId id;
	private CampaignRedemptions campaignRedemptions;
	private Orders orders;
	private String type;

	public OrdersCampaigns() {
	}

	public OrdersCampaigns(OrdersCampaignsId id, CampaignRedemptions campaignRedemptions, Orders orders, String type) {
		this.id = id;
		this.campaignRedemptions = campaignRedemptions;
		this.orders = orders;
		this.type = type;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false)),
			@AttributeOverride(name = "campaignId", column = @Column(name = "campaign_id", nullable = false)) })
	public OrdersCampaignsId getId() {
		return this.id;
	}

	public void setId(OrdersCampaignsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "campaign_id", nullable = false, insertable = false, updatable = false)
	public CampaignRedemptions getCampaignRedemptions() {
		return this.campaignRedemptions;
	}

	public void setCampaignRedemptions(CampaignRedemptions campaignRedemptions) {
		this.campaignRedemptions = campaignRedemptions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "type", nullable = false, length = 250)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
