package com.eventura.entities;
// Generated Jun 21, 2025, 1:02:58 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * OrdersCampaigns generated by hbm2java
 */
@Entity
@Table(name = "orders_campaigns")
public class OrdersCampaigns implements java.io.Serializable {

	private OrdersCampaignsId id;
	private CampaignRedemptions campaignRedemptions;
	private Orders orders;
	private Date redemtionDate;

	public OrdersCampaigns() {
	}

	public OrdersCampaigns(OrdersCampaignsId id, CampaignRedemptions campaignRedemptions, Orders orders,
			Date redemtionDate) {
		this.id = id;
		this.campaignRedemptions = campaignRedemptions;
		this.orders = orders;
		this.redemtionDate = redemtionDate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false)),
			@AttributeOverride(name = "campaignId", column = @Column(name = "campaign_id", nullable = false)) })
	public OrdersCampaignsId getId() {
		return this.id;
	}

	public void setId(OrdersCampaignsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "campaign_id", nullable = false, insertable = false, updatable = false)
	public CampaignRedemptions getCampaignRedemptions() {
		return this.campaignRedemptions;
	}

	public void setCampaignRedemptions(CampaignRedemptions campaignRedemptions) {
		this.campaignRedemptions = campaignRedemptions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "redemtion_date", nullable = false, length = 19)
	public Date getRedemtionDate() {
		return this.redemtionDate;
	}

	public void setRedemtionDate(Date redemtionDate) {
		this.redemtionDate = redemtionDate;
	}

}
