package com.eventura.entities;
// Generated Jul 2, 2025, 11:54:26 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * OrderReturns generated by hbm2java
 */
@Entity
@Table(name = "order_returns")
public class OrderReturns implements java.io.Serializable {

	private Integer id;
	private OrderItems orderItems;
	private ProductVariants productVariants;
	private Products products;
	private Integer quantity;
	private double price;
	private String orderReturnStatus;
	private Date createdAt;
	private Date updatedAt;
	private Set<OrderRefunds> orderRefundses = new HashSet<OrderRefunds>(0);

	public OrderReturns() {
	}

	public OrderReturns(OrderItems orderItems, ProductVariants productVariants, Products products, double price,
			String orderReturnStatus, Date createdAt, Date updatedAt) {
		this.orderItems = orderItems;
		this.productVariants = productVariants;
		this.products = products;
		this.price = price;
		this.orderReturnStatus = orderReturnStatus;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public OrderReturns(OrderItems orderItems, ProductVariants productVariants, Products products, Integer quantity,
			double price, String orderReturnStatus, Date createdAt, Date updatedAt, Set<OrderRefunds> orderRefundses) {
		this.orderItems = orderItems;
		this.productVariants = productVariants;
		this.products = products;
		this.quantity = quantity;
		this.price = price;
		this.orderReturnStatus = orderReturnStatus;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.orderRefundses = orderRefundses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_items_id", nullable = false)
	public OrderItems getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(OrderItems orderItems) {
		this.orderItems = orderItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_variant_id", nullable = false)
	public ProductVariants getProductVariants() {
		return this.productVariants;
	}

	public void setProductVariants(ProductVariants productVariants) {
		this.productVariants = productVariants;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "order_return_status", nullable = false)
	public String getOrderReturnStatus() {
		return this.orderReturnStatus;
	}

	public void setOrderReturnStatus(String orderReturnStatus) {
		this.orderReturnStatus = orderReturnStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderReturns")
	public Set<OrderRefunds> getOrderRefundses() {
		return this.orderRefundses;
	}

	public void setOrderRefundses(Set<OrderRefunds> orderRefundses) {
		this.orderRefundses = orderRefundses;
	}

}
