package com.eventura.entities;
// Generated Jun 22, 2025, 10:52:58 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * OrderOrderStatus generated by hbm2java
 */
@Entity
@Table(name = "order_order_status")
public class OrderOrderStatus implements java.io.Serializable {

	private OrderOrderStatusId id;
	private OrderStatus orderStatus;
	private Orders orders;
	private Date createdAt;

	public OrderOrderStatus() {
	}

	public OrderOrderStatus(OrderOrderStatusId id, OrderStatus orderStatus, Orders orders, Date createdAt) {
		this.id = id;
		this.orderStatus = orderStatus;
		this.orders = orders;
		this.createdAt = createdAt;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false)),
			@AttributeOverride(name = "orderStatusId", column = @Column(name = "order_status_id", nullable = false)) })
	public OrderOrderStatusId getId() {
		return this.id;
	}

	public void setId(OrderOrderStatusId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_status_id", nullable = false, insertable = false, updatable = false)
	public OrderStatus getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(OrderStatus orderStatus) {
		this.orderStatus = orderStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
