package com.eventura.entities;
// Generated Jun 30, 2025, 6:23:22 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * OrdersCampaignsId generated by hbm2java
 */
@Embeddable
public class OrdersCampaignsId implements java.io.Serializable {

	private int orderId;
	private int campaignId;

	public OrdersCampaignsId() {
	}

	public OrdersCampaignsId(int orderId, int campaignId) {
		this.orderId = orderId;
		this.campaignId = campaignId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "campaign_id", nullable = false)
	public int getCampaignId() {
		return this.campaignId;
	}

	public void setCampaignId(int campaignId) {
		this.campaignId = campaignId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdersCampaignsId))
			return false;
		OrdersCampaignsId castOther = (OrdersCampaignsId) other;

		return (this.getOrderId() == castOther.getOrderId()) && (this.getCampaignId() == castOther.getCampaignId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getCampaignId();
		return result;
	}

}
