package com.eventura.entities;
// Generated Jul 2, 2025, 11:54:26 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * OrderItemsOrderStatusId generated by hbm2java
 */
@Embeddable
public class OrderItemsOrderStatusId implements java.io.Serializable {

	private int orderItemId;
	private int orderStatusId;

	public OrderItemsOrderStatusId() {
	}

	public OrderItemsOrderStatusId(int orderItemId, int orderStatusId) {
		this.orderItemId = orderItemId;
		this.orderStatusId = orderStatusId;
	}

	@Column(name = "order_item_id", nullable = false)
	public int getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(int orderItemId) {
		this.orderItemId = orderItemId;
	}

	@Column(name = "order_status_id", nullable = false)
	public int getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(int orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderItemsOrderStatusId))
			return false;
		OrderItemsOrderStatusId castOther = (OrderItemsOrderStatusId) other;

		return (this.getOrderItemId() == castOther.getOrderItemId())
				&& (this.getOrderStatusId() == castOther.getOrderStatusId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderItemId();
		result = 37 * result + this.getOrderStatusId();
		return result;
	}

}
