package com.eventura.entities;
// Generated Jun 23, 2025, 6:51:08 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name = "order_status")
public class OrderStatus implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date createdAt;
	private Date deletedAt;
	private Set<OrderItemsOrderStatus> orderItemsOrderStatuses = new HashSet<OrderItemsOrderStatus>(0);

	public OrderStatus() {
	}

	public OrderStatus(String name, Date createdAt) {
		this.name = name;
		this.createdAt = createdAt;
	}

	public OrderStatus(String name, Date createdAt, Date deletedAt,
			Set<OrderItemsOrderStatus> orderItemsOrderStatuses) {
		this.name = name;
		this.createdAt = createdAt;
		this.deletedAt = deletedAt;
		this.orderItemsOrderStatuses = orderItemsOrderStatuses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 19)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderStatus")
	public Set<OrderItemsOrderStatus> getOrderItemsOrderStatuses() {
		return this.orderItemsOrderStatuses;
	}

	public void setOrderItemsOrderStatuses(Set<OrderItemsOrderStatus> orderItemsOrderStatuses) {
		this.orderItemsOrderStatuses = orderItemsOrderStatuses;
	}

}
