package com.eventura.entities;
// Generated Jul 2, 2025, 11:54:26 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * OrderItemsOrderStatus generated by hbm2java
 */
@Entity
@Table(name = "order_items_order_status")
public class OrderItemsOrderStatus implements java.io.Serializable {

	private OrderItemsOrderStatusId id;
	private OrderItems orderItems;
	private OrderStatus orderStatus;
	private Date createdAt;

	public OrderItemsOrderStatus() {
	}

	public OrderItemsOrderStatus(OrderItemsOrderStatusId id, OrderItems orderItems, OrderStatus orderStatus,
			Date createdAt) {
		this.id = id;
		this.orderItems = orderItems;
		this.orderStatus = orderStatus;
		this.createdAt = createdAt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orderItemId", column = @Column(name = "order_item_id", nullable = false)),
			@AttributeOverride(name = "orderStatusId", column = @Column(name = "order_status_id", nullable = false)) })
	public OrderItemsOrderStatusId getId() {
		return this.id;
	}

	public void setId(OrderItemsOrderStatusId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_item_id", nullable = false, insertable = false, updatable = false)
	public OrderItems getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(OrderItems orderItems) {
		this.orderItems = orderItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_status_id", nullable = false, insertable = false, updatable = false)
	public OrderStatus getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(OrderStatus orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

}
