package com.eventura.entities;
// Generated Jun 17, 2025, 7:55:23 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * OrdersCouponsId generated by hbm2java
 */
@Embeddable
public class OrdersCouponsId implements java.io.Serializable {

	private int orderId;
	private int couponId;

	public OrdersCouponsId() {
	}

	public OrdersCouponsId(int orderId, int couponId) {
		this.orderId = orderId;
		this.couponId = couponId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "coupon_id", nullable = false)
	public int getCouponId() {
		return this.couponId;
	}

	public void setCouponId(int couponId) {
		this.couponId = couponId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdersCouponsId))
			return false;
		OrdersCouponsId castOther = (OrdersCouponsId) other;

		return (this.getOrderId() == castOther.getOrderId()) && (this.getCouponId() == castOther.getCouponId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getCouponId();
		return result;
	}

}
