package com.eventura.entities;
// Generated Jun 22, 2025, 10:52:58 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * OrderOrderStatusId generated by hbm2java
 */
@Embeddable
public class OrderOrderStatusId implements java.io.Serializable {

	private int orderId;
	private int orderStatusId;

	public OrderOrderStatusId() {
	}

	public OrderOrderStatusId(int orderId, int orderStatusId) {
		this.orderId = orderId;
		this.orderStatusId = orderStatusId;
	}

	@Column(name = "order_id", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "order_status_id", nullable = false)
	public int getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(int orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderOrderStatusId))
			return false;
		OrderOrderStatusId castOther = (OrderOrderStatusId) other;

		return (this.getOrderId() == castOther.getOrderId())
				&& (this.getOrderStatusId() == castOther.getOrderStatusId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getOrderStatusId();
		return result;
	}

}
