package com.eventura.entities;
// Generated Jun 12, 2025, 2:02:47 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * OrderReturns generated by hbm2java
 */
@Entity
@Table(name = "order_returns")
public class OrderReturns implements java.io.Serializable {

	private int id;
	private OrderItems orderItems;
	private Integer productId;
	private Integer productVariantId;
	private Integer quantity;
	private Double price;
	private String orderReturnStatus;
	private Date createdAt;
	private Date updatedAt;
	private Set<OrderRefunds> orderRefundses = new HashSet<OrderRefunds>(0);

	public OrderReturns() {
	}

	public OrderReturns(int id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public OrderReturns(int id, OrderItems orderItems, Integer productId, Integer productVariantId, Integer quantity,
			Double price, String orderReturnStatus, Date createdAt, Date updatedAt, Set<OrderRefunds> orderRefundses) {
		this.id = id;
		this.orderItems = orderItems;
		this.productId = productId;
		this.productVariantId = productVariantId;
		this.quantity = quantity;
		this.price = price;
		this.orderReturnStatus = orderReturnStatus;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.orderRefundses = orderRefundses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_items_id")
	public OrderItems getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(OrderItems orderItems) {
		this.orderItems = orderItems;
	}

	@Column(name = "product_id")
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "product_variant_id")
	public Integer getProductVariantId() {
		return this.productVariantId;
	}

	public void setProductVariantId(Integer productVariantId) {
		this.productVariantId = productVariantId;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "order_return_status")
	public String getOrderReturnStatus() {
		return this.orderReturnStatus;
	}

	public void setOrderReturnStatus(String orderReturnStatus) {
		this.orderReturnStatus = orderReturnStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderReturns")
	public Set<OrderRefunds> getOrderRefundses() {
		return this.orderRefundses;
	}

	public void setOrderRefundses(Set<OrderRefunds> orderRefundses) {
		this.orderRefundses = orderRefundses;
	}

}
