package com.eventura.entities;
// Generated Jun 21, 2025, 7:41:27 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * ProductVariants generated by hbm2java
 */
@Entity
@Table(name = "product_variants")
public class ProductVariants implements java.io.Serializable {

	private Integer id;
	private ProductAttributes productAttributes;
	private Products products;
	private String value;
	private Double additionalPrice;
	private Date createdAt;
	private Date updatedAt;
	private Set<OrderReturns> orderReturnses = new HashSet<OrderReturns>(0);
	private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);

	public ProductVariants() {
	}

	public ProductVariants(ProductAttributes productAttributes, Products products, String value, Date createdAt,
			Date updatedAt) {
		this.productAttributes = productAttributes;
		this.products = products;
		this.value = value;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ProductVariants(ProductAttributes productAttributes, Products products, String value, Double additionalPrice,
			Date createdAt, Date updatedAt, Set<OrderReturns> orderReturnses, Set<OrderItems> orderItemses) {
		this.productAttributes = productAttributes;
		this.products = products;
		this.value = value;
		this.additionalPrice = additionalPrice;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.orderReturnses = orderReturnses;
		this.orderItemses = orderItemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_attribute_id", nullable = false)
	public ProductAttributes getProductAttributes() {
		return this.productAttributes;
	}

	public void setProductAttributes(ProductAttributes productAttributes) {
		this.productAttributes = productAttributes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "additional_price", precision = 22, scale = 0)
	public Double getAdditionalPrice() {
		return this.additionalPrice;
	}

	public void setAdditionalPrice(Double additionalPrice) {
		this.additionalPrice = additionalPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productVariants")
	public Set<OrderReturns> getOrderReturnses() {
		return this.orderReturnses;
	}

	public void setOrderReturnses(Set<OrderReturns> orderReturnses) {
		this.orderReturnses = orderReturnses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productVariants")
	public Set<OrderItems> getOrderItemses() {
		return this.orderItemses;
	}

	public void setOrderItemses(Set<OrderItems> orderItemses) {
		this.orderItemses = orderItemses;
	}

}
