package com.eventura.entities;
// Generated Jun 12, 2025, 2:02:47 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products")
public class Products implements java.io.Serializable {

	private int id;
	private ProductCategories productCategories;
	private Vendors vendors;
	private String name;
	private String description;
	private Double price;
	private Date createdAt;
	private Date updatedAt;
	private Date deletedAt;
	private Set<ProductVariants> productVariantses = new HashSet<ProductVariants>(0);
	private Set<ProductReviews> productReviewses = new HashSet<ProductReviews>(0);
	private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);

	public Products() {
	}

	public Products(int id, Date createdAt, Date updatedAt, Date deletedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
	}

	public Products(int id, ProductCategories productCategories, Vendors vendors, String name, String description,
			Double price, Date createdAt, Date updatedAt, Date deletedAt, Set<ProductVariants> productVariantses,
			Set<ProductReviews> productReviewses, Set<OrderItems> orderItemses) {
		this.id = id;
		this.productCategories = productCategories;
		this.vendors = vendors;
		this.name = name;
		this.description = description;
		this.price = price;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.deletedAt = deletedAt;
		this.productVariantses = productVariantses;
		this.productReviewses = productReviewses;
		this.orderItemses = orderItemses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public ProductCategories getProductCategories() {
		return this.productCategories;
	}

	public void setProductCategories(ProductCategories productCategories) {
		this.productCategories = productCategories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor_id")
	public Vendors getVendors() {
		return this.vendors;
	}

	public void setVendors(Vendors vendors) {
		this.vendors = vendors;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", nullable = false, length = 19)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<ProductVariants> getProductVariantses() {
		return this.productVariantses;
	}

	public void setProductVariantses(Set<ProductVariants> productVariantses) {
		this.productVariantses = productVariantses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<ProductReviews> getProductReviewses() {
		return this.productReviewses;
	}

	public void setProductReviewses(Set<ProductReviews> productReviewses) {
		this.productReviewses = productReviewses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<OrderItems> getOrderItemses() {
		return this.orderItemses;
	}

	public void setOrderItemses(Set<OrderItems> orderItemses) {
		this.orderItemses = orderItemses;
	}

}
