package com.eventura.entities;
// Generated Jun 12, 2025, 2:02:47 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * UserAddressId generated by hbm2java
 */
@Embeddable
public class UserAddressId implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private String address;
	private String provinceCode;
	private String districtCode;
	private String wardCode;

	public UserAddressId() {
	}

	public UserAddressId(Integer id, Integer userId, String address, String provinceCode, String districtCode,
			String wardCode) {
		this.id = id;
		this.userId = userId;
		this.address = address;
		this.provinceCode = provinceCode;
		this.districtCode = districtCode;
		this.wardCode = wardCode;
	}

	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "province_code")
	public String getProvinceCode() {
		return this.provinceCode;
	}

	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}

	@Column(name = "district_code")
	public String getDistrictCode() {
		return this.districtCode;
	}

	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode;
	}

	@Column(name = "ward_code")
	public String getWardCode() {
		return this.wardCode;
	}

	public void setWardCode(String wardCode) {
		this.wardCode = wardCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserAddressId))
			return false;
		UserAddressId castOther = (UserAddressId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getAddress() == castOther.getAddress()) || (this.getAddress() != null
						&& castOther.getAddress() != null && this.getAddress().equals(castOther.getAddress())))
				&& ((this.getProvinceCode() == castOther.getProvinceCode())
						|| (this.getProvinceCode() != null && castOther.getProvinceCode() != null
								&& this.getProvinceCode().equals(castOther.getProvinceCode())))
				&& ((this.getDistrictCode() == castOther.getDistrictCode())
						|| (this.getDistrictCode() != null && castOther.getDistrictCode() != null
								&& this.getDistrictCode().equals(castOther.getDistrictCode())))
				&& ((this.getWardCode() == castOther.getWardCode()) || (this.getWardCode() != null
						&& castOther.getWardCode() != null && this.getWardCode().equals(castOther.getWardCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result + (getProvinceCode() == null ? 0 : this.getProvinceCode().hashCode());
		result = 37 * result + (getDistrictCode() == null ? 0 : this.getDistrictCode().hashCode());
		result = 37 * result + (getWardCode() == null ? 0 : this.getWardCode().hashCode());
		return result;
	}

}
