package com.eventura.entities;
// Generated Jun 12, 2025, 2:02:47 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * UserAddress generated by hbm2java
 */
@Entity
@Table(name = "user_address")
public class UserAddress implements java.io.Serializable {

	private UserAddressId id;
	private Districts districts;
	private Provinces provinces;
	private Users users;
	private Wards wards;

	public UserAddress() {
	}

	public UserAddress(UserAddressId id) {
		this.id = id;
	}

	public UserAddress(UserAddressId id, Districts districts, Provinces provinces, Users users, Wards wards) {
		this.id = id;
		this.districts = districts;
		this.provinces = provinces;
		this.users = users;
		this.wards = wards;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id")),
			@AttributeOverride(name = "address", column = @Column(name = "address")),
			@AttributeOverride(name = "provinceCode", column = @Column(name = "province_code")),
			@AttributeOverride(name = "districtCode", column = @Column(name = "district_code")),
			@AttributeOverride(name = "wardCode", column = @Column(name = "ward_code")) })
	public UserAddressId getId() {
		return this.id;
	}

	public void setId(UserAddressId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "district_code", insertable = false, updatable = false)
	public Districts getDistricts() {
		return this.districts;
	}

	public void setDistricts(Districts districts) {
		this.districts = districts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "province_code", insertable = false, updatable = false)
	public Provinces getProvinces() {
		return this.provinces;
	}

	public void setProvinces(Provinces provinces) {
		this.provinces = provinces;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ward_code", insertable = false, updatable = false)
	public Wards getWards() {
		return this.wards;
	}

	public void setWards(Wards wards) {
		this.wards = wards;
	}

}
