package com.eventura.entities;
// Generated Jun 30, 2025, 6:31:20 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * UserAddress generated by hbm2java
 */
@Entity
@Table(name = "user_address")
public class UserAddress implements java.io.Serializable {

	private Integer id;
	private Districts districts;
	private Provinces provinces;
	private Users users;
	private Wards wards;
	private String address;
	private Date createdAt;
	private Date deletedAt;
	private String name;

	public UserAddress() {
	}

	public UserAddress(Districts districts, Provinces provinces, Users users, Wards wards, String address,
			Date createdAt, String name) {
		this.districts = districts;
		this.provinces = provinces;
		this.users = users;
		this.wards = wards;
		this.address = address;
		this.createdAt = createdAt;
		this.name = name;
	}

	public UserAddress(Districts districts, Provinces provinces, Users users, Wards wards, String address,
			Date createdAt, Date deletedAt, String name) {
		this.districts = districts;
		this.provinces = provinces;
		this.users = users;
		this.wards = wards;
		this.address = address;
		this.createdAt = createdAt;
		this.deletedAt = deletedAt;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "district_code", nullable = false)
	public Districts getDistricts() {
		return this.districts;
	}

	public void setDistricts(Districts districts) {
		this.districts = districts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "province_code", nullable = false)
	public Provinces getProvinces() {
		return this.provinces;
	}

	public void setProvinces(Provinces provinces) {
		this.provinces = provinces;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ward_code", nullable = false)
	public Wards getWards() {
		return this.wards;
	}

	public void setWards(Wards wards) {
		this.wards = wards;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 19)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
