package com.eventura.entities;
// Generated Jun 22, 2025, 10:52:58 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", uniqueConstraints = { @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "username") })
public class Users implements java.io.Serializable {

	private Integer id;
	private Roles roles;
	private String avatar;
	private String firstName;
	private String lastName;
	private String username;
	private String email;
	private String rememberToken;
	private String password;
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date birthOfDate;
	private String phoneNumber;
	private Date createdAt;
	private Date deletedAt;
	private Set<VendorReviews> vendorReviewses = new HashSet<VendorReviews>(0);
	private Vendors vendors;
	private Set<Carts> cartses = new HashSet<Carts>(0);
	private Set<ProductReviews> productReviewses = new HashSet<ProductReviews>(0);
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<ActivityLog> activityLogs = new HashSet<ActivityLog>(0);
	private Set<UserAddress> userAddresses = new HashSet<UserAddress>(0);

	public Users() {
	}

	public Users(Roles roles, String avatar, String firstName, String lastName, String username, String email,
			String password, Date birthOfDate, String phoneNumber, Date createdAt) {
		this.roles = roles;
		this.avatar = avatar;
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.email = email;
		this.password = password;
		this.birthOfDate = birthOfDate;
		this.phoneNumber = phoneNumber;
		this.createdAt = createdAt;
	}

	public Users(Roles roles, String avatar, String firstName, String lastName, String username, String email,
			String rememberToken, String password, Date birthOfDate, String phoneNumber, Date createdAt, Date deletedAt,
			Set<VendorReviews> vendorReviewses, Vendors vendors, Set<Carts> cartses,
			Set<ProductReviews> productReviewses, Set<Orders> orderses, Set<ActivityLog> activityLogs,
			Set<UserAddress> userAddresses) {
		this.roles = roles;
		this.avatar = avatar;
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.email = email;
		this.rememberToken = rememberToken;
		this.password = password;
		this.birthOfDate = birthOfDate;
		this.phoneNumber = phoneNumber;
		this.createdAt = createdAt;
		this.deletedAt = deletedAt;
		this.vendorReviewses = vendorReviewses;
		this.vendors = vendors;
		this.cartses = cartses;
		this.productReviewses = productReviewses;
		this.orderses = orderses;
		this.activityLogs = activityLogs;
		this.userAddresses = userAddresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@Column(name = "avatar", nullable = false)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "first_name", nullable = false)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "username", unique = true, nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "remember_token")
	public String getRememberToken() {
		return this.rememberToken;
	}

	public void setRememberToken(String rememberToken) {
		this.rememberToken = rememberToken;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birth_of_date", nullable = false, length = 10)
	public Date getBirthOfDate() {
		return this.birthOfDate;
	}

	public void setBirthOfDate(Date birthOfDate) {
		this.birthOfDate = birthOfDate;
	}

	@Column(name = "phone_number", nullable = false)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 19)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<VendorReviews> getVendorReviewses() {
		return this.vendorReviewses;
	}

	public void setVendorReviewses(Set<VendorReviews> vendorReviewses) {
		this.vendorReviewses = vendorReviewses;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "users")
	public Vendors getVendors() {
		return this.vendors;
	}

	public void setVendors(Vendors vendors) {
		this.vendors = vendors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Carts> getCartses() {
		return this.cartses;
	}

	public void setCartses(Set<Carts> cartses) {
		this.cartses = cartses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<ProductReviews> getProductReviewses() {
		return this.productReviewses;
	}

	public void setProductReviewses(Set<ProductReviews> productReviewses) {
		this.productReviewses = productReviewses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<ActivityLog> getActivityLogs() {
		return this.activityLogs;
	}

	public void setActivityLogs(Set<ActivityLog> activityLogs) {
		this.activityLogs = activityLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserAddress> getUserAddresses() {
		return this.userAddresses;
	}

	public void setUserAddresses(Set<UserAddress> userAddresses) {
		this.userAddresses = userAddresses;
	}

}
