package com.eventura.entities;
// Generated Jun 12, 2025, 2:02:47 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Vendors generated by hbm2java
 */
@Entity
@Table(name = "vendors")
public class Vendors implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private String contactName;
	private String contactEmail;
	private Date createdAt;
	private Date updatedAt;
	private Users users;
	private Set<Commissions> commissionses = new HashSet<Commissions>(0);
	private Set<VendorReviews> vendorReviewses = new HashSet<VendorReviews>(0);
	private Set<Products> productses = new HashSet<Products>(0);
	private Set<VendorsSettings> vendorsSettingses = new HashSet<VendorsSettings>(0);
	private Set<VendorEarnings> vendorEarningses = new HashSet<VendorEarnings>(0);

	public Vendors() {
	}

	public Vendors(int id, Date createdAt, Date updatedAt) {
		this.id = id;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Vendors(int id, String name, String description, String contactName, String contactEmail, Date createdAt,
			Date updatedAt, Users users, Set<Commissions> commissionses, Set<VendorReviews> vendorReviewses,
			Set<Products> productses, Set<VendorsSettings> vendorsSettingses, Set<VendorEarnings> vendorEarningses) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.contactName = contactName;
		this.contactEmail = contactEmail;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.users = users;
		this.commissionses = commissionses;
		this.vendorReviewses = vendorReviewses;
		this.productses = productses;
		this.vendorsSettingses = vendorsSettingses;
		this.vendorEarningses = vendorEarningses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "contact_name")
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "contact_email")
	public String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<Commissions> getCommissionses() {
		return this.commissionses;
	}

	public void setCommissionses(Set<Commissions> commissionses) {
		this.commissionses = commissionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<VendorReviews> getVendorReviewses() {
		return this.vendorReviewses;
	}

	public void setVendorReviewses(Set<VendorReviews> vendorReviewses) {
		this.vendorReviewses = vendorReviewses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<VendorsSettings> getVendorsSettingses() {
		return this.vendorsSettingses;
	}

	public void setVendorsSettingses(Set<VendorsSettings> vendorsSettingses) {
		this.vendorsSettingses = vendorsSettingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<VendorEarnings> getVendorEarningses() {
		return this.vendorEarningses;
	}

	public void setVendorEarningses(Set<VendorEarnings> vendorEarningses) {
		this.vendorEarningses = vendorEarningses;
	}

}
