package com.eventura.entities;
// Generated Jun 19, 2025, 1:15:05 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * VendorSettings generated by hbm2java
 */
@Entity
@Table(name = "vendor_settings")
public class VendorSettings implements java.io.Serializable {

	private Integer id;
	private Vendors vendors;
	private String vendorType;
	private Double commissionValue;
	private Date createdAt;
	private Date updatedAt;

	public VendorSettings() {
	}

	public VendorSettings(Date createdAt, Date updatedAt) {
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public VendorSettings(Vendors vendors, String vendorType, Double commissionValue, Date createdAt, Date updatedAt) {
		this.vendors = vendors;
		this.vendorType = vendorType;
		this.commissionValue = commissionValue;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor_id")
	public Vendors getVendors() {
		return this.vendors;
	}

	public void setVendors(Vendors vendors) {
		this.vendors = vendors;
	}

	@Column(name = "vendor_type")
	public String getVendorType() {
		return this.vendorType;
	}

	public void setVendorType(String vendorType) {
		this.vendorType = vendorType;
	}

	@Column(name = "commission_value", precision = 22, scale = 0)
	public Double getCommissionValue() {
		return this.commissionValue;
	}

	public void setCommissionValue(Double commissionValue) {
		this.commissionValue = commissionValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
