package com.eventura.entities;
// Generated Jun 21, 2025, 10:45:01 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * VendorProductCategory generated by hbm2java
 */
@Entity
@Table(name = "vendor_product_category")
public class VendorProductCategory implements java.io.Serializable {

	private Integer id;
	private VendorProductCategory vendorProductCategory;
	private Vendors vendors;
	private Set<VendorProductCategory> vendorProductCategories = new HashSet<VendorProductCategory>(0);

	public VendorProductCategory() {
	}

	public VendorProductCategory(VendorProductCategory vendorProductCategory, Vendors vendors) {
		this.vendorProductCategory = vendorProductCategory;
		this.vendors = vendors;
	}

	public VendorProductCategory(VendorProductCategory vendorProductCategory, Vendors vendors,
			Set<VendorProductCategory> vendorProductCategories) {
		this.vendorProductCategory = vendorProductCategory;
		this.vendors = vendors;
		this.vendorProductCategories = vendorProductCategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_category_id", nullable = false)
	public VendorProductCategory getVendorProductCategory() {
		return this.vendorProductCategory;
	}

	public void setVendorProductCategory(VendorProductCategory vendorProductCategory) {
		this.vendorProductCategory = vendorProductCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor_id", nullable = false)
	public Vendors getVendors() {
		return this.vendors;
	}

	public void setVendors(Vendors vendors) {
		this.vendors = vendors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendorProductCategory")
	public Set<VendorProductCategory> getVendorProductCategories() {
		return this.vendorProductCategories;
	}

	public void setVendorProductCategories(Set<VendorProductCategory> vendorProductCategories) {
		this.vendorProductCategories = vendorProductCategories;
	}

}
