package com.eventura.entities;
// Generated Jun 23, 2025, 6:51:08 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VendorProductCategory generated by hbm2java
 */
@Entity
@Table(name = "vendor_product_category")
public class VendorProductCategory implements java.io.Serializable {

	private Integer id;
	private ProductCategories productCategories;
	private Vendors vendors;

	public VendorProductCategory() {
	}

	public VendorProductCategory(ProductCategories productCategories, Vendors vendors) {
		this.productCategories = productCategories;
		this.vendors = vendors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_category_id", nullable = false)
	public ProductCategories getProductCategories() {
		return this.productCategories;
	}

	public void setProductCategories(ProductCategories productCategories) {
		this.productCategories = productCategories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendor_id", nullable = false)
	public Vendors getVendors() {
		return this.vendors;
	}

	public void setVendors(Vendors vendors) {
		this.vendors = vendors;
	}

}
