package com.eventura.entities;
// Generated Jun 21, 2025, 10:45:01 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * VendorSettings generated by hbm2java
 */
@Entity
@Table(name = "vendor_settings")
public class VendorSettings implements java.io.Serializable {

	private Integer id;
	private String vendorType;
	private double commissionValue;
	private Date createdAt;
	private Date updatedAt;
	private Set<Vendors> vendorses = new HashSet<Vendors>(0);

	public VendorSettings() {
	}

	public VendorSettings(String vendorType, double commissionValue, Date createdAt, Date updatedAt) {
		this.vendorType = vendorType;
		this.commissionValue = commissionValue;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public VendorSettings(String vendorType, double commissionValue, Date createdAt, Date updatedAt,
			Set<Vendors> vendorses) {
		this.vendorType = vendorType;
		this.commissionValue = commissionValue;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.vendorses = vendorses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "vendor_type", nullable = false)
	public String getVendorType() {
		return this.vendorType;
	}

	public void setVendorType(String vendorType) {
		this.vendorType = vendorType;
	}

	@Column(name = "commission_value", nullable = false, precision = 22, scale = 0)
	public double getCommissionValue() {
		return this.commissionValue;
	}

	public void setCommissionValue(double commissionValue) {
		this.commissionValue = commissionValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendorSettings")
	public Set<Vendors> getVendorses() {
		return this.vendorses;
	}

	public void setVendorses(Set<Vendors> vendorses) {
		this.vendorses = vendorses;
	}

}
