package com.eventura.entities;
// Generated Jun 17, 2025, 7:55:23 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Vendors generated by hbm2java
 */
@Entity
@Table(name = "vendors")
public class Vendors implements java.io.Serializable {

	private Integer id;
	private Users users;
	private String name;
	private String description;
	private String contactName;
	private String contactEmail;
	private Date createdAt;
	private Date updatedAt;
	private Set<Commissions> commissionses = new HashSet<Commissions>(0);
	private Set<VendorReviews> vendorReviewses = new HashSet<VendorReviews>(0);
	private Set<Products> productses = new HashSet<Products>(0);
	private Set<VendorSettings> vendorSettingses = new HashSet<VendorSettings>(0);
	private Set<VendorEarnings> vendorEarningses = new HashSet<VendorEarnings>(0);
	private Set<Coupons> couponses = new HashSet<Coupons>(0);

	public Vendors() {
	}

	public Vendors(Users users, Date createdAt, Date updatedAt) {
		this.users = users;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Vendors(Users users, String name, String description, String contactName, String contactEmail,
			Date createdAt, Date updatedAt, Set<Commissions> commissionses, Set<VendorReviews> vendorReviewses,
			Set<Products> productses, Set<VendorSettings> vendorSettingses, Set<VendorEarnings> vendorEarningses,
			Set<Coupons> couponses) {
		this.users = users;
		this.name = name;
		this.description = description;
		this.contactName = contactName;
		this.contactEmail = contactEmail;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.commissionses = commissionses;
		this.vendorReviewses = vendorReviewses;
		this.productses = productses;
		this.vendorSettingses = vendorSettingses;
		this.vendorEarningses = vendorEarningses;
		this.couponses = couponses;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "users"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "contact_name")
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "contact_email")
	public String getContactEmail() {
		return this.contactEmail;
	}

	public void setContactEmail(String contactEmail) {
		this.contactEmail = contactEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<Commissions> getCommissionses() {
		return this.commissionses;
	}

	public void setCommissionses(Set<Commissions> commissionses) {
		this.commissionses = commissionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<VendorReviews> getVendorReviewses() {
		return this.vendorReviewses;
	}

	public void setVendorReviewses(Set<VendorReviews> vendorReviewses) {
		this.vendorReviewses = vendorReviewses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<VendorSettings> getVendorSettingses() {
		return this.vendorSettingses;
	}

	public void setVendorSettingses(Set<VendorSettings> vendorSettingses) {
		this.vendorSettingses = vendorSettingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<VendorEarnings> getVendorEarningses() {
		return this.vendorEarningses;
	}

	public void setVendorEarningses(Set<VendorEarnings> vendorEarningses) {
		this.vendorEarningses = vendorEarningses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<Coupons> getCouponses() {
		return this.couponses;
	}

	public void setCouponses(Set<Coupons> couponses) {
		this.couponses = couponses;
	}

}
