package com.eventura.entities;
// Generated Jun 27, 2025, 5:59:04 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * VouchersCampaignsId generated by hbm2java
 */
@Embeddable
public class VouchersCampaignsId implements java.io.Serializable {

	private int voucherId;
	private int campaignId;

	public VouchersCampaignsId() {
	}

	public VouchersCampaignsId(int voucherId, int campaignId) {
		this.voucherId = voucherId;
		this.campaignId = campaignId;
	}

	@Column(name = "voucher_id", nullable = false)
	public int getVoucherId() {
		return this.voucherId;
	}

	public void setVoucherId(int voucherId) {
		this.voucherId = voucherId;
	}

	@Column(name = "campaign_id", nullable = false)
	public int getCampaignId() {
		return this.campaignId;
	}

	public void setCampaignId(int campaignId) {
		this.campaignId = campaignId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VouchersCampaignsId))
			return false;
		VouchersCampaignsId castOther = (VouchersCampaignsId) other;

		return (this.getVoucherId() == castOther.getVoucherId()) && (this.getCampaignId() == castOther.getCampaignId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVoucherId();
		result = 37 * result + this.getCampaignId();
		return result;
	}

}
