package com.eventura.entities;
// Generated Jul 2, 2025, 11:54:26 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VouchersCampaigns generated by hbm2java
 */
@Entity
@Table(name = "vouchers_campaigns")
public class VouchersCampaigns implements java.io.Serializable {

	private String voucherCode;
	private CampaignRedemptions campaignRedemptions;
	private Vouchers vouchers;
	private int redeemAllowedQty;
	private int redeemUsedQty;

	public VouchersCampaigns() {
	}

	public VouchersCampaigns(String voucherCode, CampaignRedemptions campaignRedemptions, Vouchers vouchers,
			int redeemAllowedQty, int redeemUsedQty) {
		this.voucherCode = voucherCode;
		this.campaignRedemptions = campaignRedemptions;
		this.vouchers = vouchers;
		this.redeemAllowedQty = redeemAllowedQty;
		this.redeemUsedQty = redeemUsedQty;
	}

	@Id

	@Column(name = "voucher_code", unique = true, nullable = false)
	public String getVoucherCode() {
		return this.voucherCode;
	}

	public void setVoucherCode(String voucherCode) {
		this.voucherCode = voucherCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "campaign_id", nullable = false)
	public CampaignRedemptions getCampaignRedemptions() {
		return this.campaignRedemptions;
	}

	public void setCampaignRedemptions(CampaignRedemptions campaignRedemptions) {
		this.campaignRedemptions = campaignRedemptions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "voucher_id", nullable = false)
	public Vouchers getVouchers() {
		return this.vouchers;
	}

	public void setVouchers(Vouchers vouchers) {
		this.vouchers = vouchers;
	}

	@Column(name = "redeem_allowed_qty", nullable = false)
	public int getRedeemAllowedQty() {
		return this.redeemAllowedQty;
	}

	public void setRedeemAllowedQty(int redeemAllowedQty) {
		this.redeemAllowedQty = redeemAllowedQty;
	}

	@Column(name = "redeem_used_qty", nullable = false)
	public int getRedeemUsedQty() {
		return this.redeemUsedQty;
	}

	public void setRedeemUsedQty(int redeemUsedQty) {
		this.redeemUsedQty = redeemUsedQty;
	}

}
