package com.eventura.entities;
// Generated Jun 24, 2025, 5:03:57 PM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VouchersCampaigns generated by hbm2java
 */
@Entity
@Table(name = "vouchers_campaigns")
public class VouchersCampaigns implements java.io.Serializable {

	private VouchersCampaignsId id;
	private CampaignRedemptions campaignRedemptions;
	private Vouchers vouchers;
	private String voucherCode;
	private int redeemAllowedQty;
	private int redeemUsedQty;

	public VouchersCampaigns() {
	}

	public VouchersCampaigns(VouchersCampaignsId id, CampaignRedemptions campaignRedemptions, Vouchers vouchers,
			int redeemAllowedQty, int redeemUsedQty) {
		this.id = id;
		this.campaignRedemptions = campaignRedemptions;
		this.vouchers = vouchers;
		this.redeemAllowedQty = redeemAllowedQty;
		this.redeemUsedQty = redeemUsedQty;
	}

	public VouchersCampaigns(VouchersCampaignsId id, CampaignRedemptions campaignRedemptions, Vouchers vouchers,
			String voucherCode, int redeemAllowedQty, int redeemUsedQty) {
		this.id = id;
		this.campaignRedemptions = campaignRedemptions;
		this.vouchers = vouchers;
		this.voucherCode = voucherCode;
		this.redeemAllowedQty = redeemAllowedQty;
		this.redeemUsedQty = redeemUsedQty;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "voucherId", column = @Column(name = "voucher_id", nullable = false)),
			@AttributeOverride(name = "campaignId", column = @Column(name = "campaign_id", nullable = false)) })
	public VouchersCampaignsId getId() {
		return this.id;
	}

	public void setId(VouchersCampaignsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "campaign_id", nullable = false, insertable = false, updatable = false)
	public CampaignRedemptions getCampaignRedemptions() {
		return this.campaignRedemptions;
	}

	public void setCampaignRedemptions(CampaignRedemptions campaignRedemptions) {
		this.campaignRedemptions = campaignRedemptions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "voucher_id", nullable = false, insertable = false, updatable = false)
	public Vouchers getVouchers() {
		return this.vouchers;
	}

	public void setVouchers(Vouchers vouchers) {
		this.vouchers = vouchers;
	}

	@Column(name = "voucher_code")
	public String getVoucherCode() {
		return this.voucherCode;
	}

	public void setVoucherCode(String voucherCode) {
		this.voucherCode = voucherCode;
	}

	@Column(name = "redeem_allowed_qty", nullable = false)
	public int getRedeemAllowedQty() {
		return this.redeemAllowedQty;
	}

	public void setRedeemAllowedQty(int redeemAllowedQty) {
		this.redeemAllowedQty = redeemAllowedQty;
	}

	@Column(name = "redeem_used_qty", nullable = false)
	public int getRedeemUsedQty() {
		return this.redeemUsedQty;
	}

	public void setRedeemUsedQty(int redeemUsedQty) {
		this.redeemUsedQty = redeemUsedQty;
	}

}
