package com.eventura.entities;
// Generated Jun 29, 2025, 6:40:48 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Wards generated by hbm2java
 */
@Entity
@Table(name = "wards")
public class Wards implements java.io.Serializable {

	private String code;
	private AdministrativeUnits administrativeUnits;
	private Districts districts;
	private String name;
	private String nameEn;
	private String fullName;
	private String fullNameEn;
	private String codeName;
	private Set<UserAddress> userAddresses = new HashSet<UserAddress>(0);

	public Wards() {
	}

	public Wards(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public Wards(String code, AdministrativeUnits administrativeUnits, Districts districts, String name, String nameEn,
			String fullName, String fullNameEn, String codeName, Set<UserAddress> userAddresses) {
		this.code = code;
		this.administrativeUnits = administrativeUnits;
		this.districts = districts;
		this.name = name;
		this.nameEn = nameEn;
		this.fullName = fullName;
		this.fullNameEn = fullNameEn;
		this.codeName = codeName;
		this.userAddresses = userAddresses;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "administrative_unit_id")
	public AdministrativeUnits getAdministrativeUnits() {
		return this.administrativeUnits;
	}

	public void setAdministrativeUnits(AdministrativeUnits administrativeUnits) {
		this.administrativeUnits = administrativeUnits;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "district_code")
	public Districts getDistricts() {
		return this.districts;
	}

	public void setDistricts(Districts districts) {
		this.districts = districts;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "name_en")
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@Column(name = "full_name")
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "full_name_en")
	public String getFullNameEn() {
		return this.fullNameEn;
	}

	public void setFullNameEn(String fullNameEn) {
		this.fullNameEn = fullNameEn;
	}

	@Column(name = "code_name")
	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "wards")
	public Set<UserAddress> getUserAddresses() {
		return this.userAddresses;
	}

	public void setUserAddresses(Set<UserAddress> userAddresses) {
		this.userAddresses = userAddresses;
	}

}
